[build]
  command = "yarn run build"
  publish = "target/dist"

[build.environment]
  NODE_VERSION = "10.4.0"
  YARN_VERSION = "1.7.0"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
